"""add video category

Revision ID: 0fcd3d25c8eb
Revises: da3f28b6c662
Create Date: 2024-12-07 21:52:59.482797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fcd3d25c8eb'
down_revision: Union[str, None] = 'da3f28b6c662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_code', sa.String(length=60), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['note_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_code')
    )
    op.add_column('videos', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'videos', 'video_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_column('videos', 'category_id')
    op.drop_table('video_categories')
    # ### end Alembic commands ###
