"""make batch_id unique live classes

Revision ID: 4797e37c9d7f
Revises: 85456f97e4c3
Create Date: 2024-11-25 12:36:31.934160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4797e37c9d7f'
down_revision: Union[str, None] = '85456f97e4c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'live-classes', ['batch_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'live-classes', type_='unique')
    # ### end Alembic commands ###
