"""batch correction

Revision ID: 4c8273c40efe
Revises: cfed507d06c6
Create Date: 2024-11-18 18:09:02.453942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c8273c40efe'
down_revision: Union[str, None] = 'cfed507d06c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('target', sa.String(), nullable=False))
    op.drop_column('batches', 'batch_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('batch_year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('batches', 'target')
    # ### end Alembic commands ###
