"""add note category to notes

Revision ID: 7d0435dad15c
Revises: 4797e37c9d7f
Create Date: 2024-11-26 10:50:35.428885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d0435dad15c'
down_revision: Union[str, None] = '4797e37c9d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_categories',
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['note_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('live-classes', sa.Column('class_name', sa.String(), nullable=False))
    op.add_column('notes', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notes', 'note_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'category_id')
    op.drop_column('live-classes', 'class_name')
    op.drop_table('note_categories')
    # ### end Alembic commands ###
