"""add live date and time

Revision ID: 85456f97e4c3
Revises: 8d13be7a91ef
Create Date: 2024-11-25 12:33:59.088314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85456f97e4c3'
down_revision: Union[str, None] = '8d13be7a91ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live-classes', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('live-classes', sa.Column('end_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live-classes', 'end_time')
    op.drop_column('live-classes', 'start_time')
    # ### end Alembic commands ###
