"""student and batch

Revision ID: cfed507d06c6
Revises: 1f037f0866fa
Create Date: 2024-11-18 13:23:55.225863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfed507d06c6'
down_revision: Union[str, None] = '1f037f0866fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('batch_name', sa.String(), nullable=False),
    sa.Column('batch_code', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('board', sa.String(), nullable=True),
    sa.Column('batch_year', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('note_link', sa.String(), nullable=False),
    sa.Column('note_description', sa.String(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('student_code', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('student_code')
    )
    op.create_table('videos',
    sa.Column('video_title', sa.String(), nullable=False),
    sa.Column('video_link', sa.String(), nullable=False),
    sa.Column('video_description', sa.String(), nullable=False),
    sa.Column('video_type', sa.String(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_profiles',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_photo', sa.String(), nullable=True),
    sa.Column('father_phone_number', sa.String(), nullable=True),
    sa.Column('mother_phone_number', sa.String(), nullable=True),
    sa.Column('siblings_phone_number', sa.String(), nullable=True),
    sa.Column('personal_number', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('school_name', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('blood_group', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_profiles')
    op.drop_table('videos')
    op.drop_table('students')
    op.drop_table('notes')
    op.drop_table('batches')
    # ### end Alembic commands ###
