"""add batch to note category

Revision ID: da3f28b6c662
Revises: 7d0435dad15c
Create Date: 2024-11-29 20:26:36.001567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da3f28b6c662'
down_revision: Union[str, None] = '7d0435dad15c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_categories', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'note_categories', 'batches', ['batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note_categories', type_='foreignkey')
    op.drop_column('note_categories', 'batch_id')
    # ### end Alembic commands ###
